### ISSUE TITLE
Desbloquear funções proibidas da engine de scripting do game

### ISSUE THREAD

**Issue by brennovictor** [felipedavid/glider#6]
A função no endereço “0x00704CD0” recebe uma string de caracteres como argumento que contém código em Lua e executa esse código na scripting engine, só que algumas funções dessa engine como Jump() e CastSpellById() foram bloqueadas pelos desenvolvedores, e devem ser desbloqueadas.

**Comment by felipedavid** [comment]
Funcionalidade implementada na função "Cheats::unlock_lua()".
